### ISSUE TITLE
Error test Momo 

### ISSUE THREAD

**Issue by N-HaoTien** [boolfly/momo-wallet#1]
When i scan the qr code on my phone it says partner data not found or not activated 
![z3502269240565_20e41a049b6af303608e1cfb5297e861](https://user-images.githubusercontent.com/96223794/174435435-fb2aa7d6-4ce5-44fd-b86e-2df899f94e77.jpg)

**Comment by mrkhoa99** [comment]
@N-HaoTien please add more details to reproduce this issue. We need step by step to replicate this issue.
